import os
from elevenlabs import generate, save, set_api_key, Voice, VoiceSettings
from dotenv import load_dotenv

load_dotenv()

set_api_key(os.environ.get("ELEVEN_LABS_API_KEY"))

voice_settings = VoiceSettings(stability=0.4, similarity_boost=0.8, style=0.1, use_speaker_boost=True)

# Using the voice id of existing cloned voice of Paul Graham, it is way more faster that creating a new voice each time. 
# It is cloned using samples from the samples/short folder generated by the samples.py script
voice = Voice(
    voice_id="iCJKLCm0V5LAXQvAjari",
    settings=voice_settings
)

def generate_essay_voiceover(title):

    # voice = clone(
    #     name="Paul Graham",
    #     files=list(map(lambda x: './samples/short/' + x, os.listdir('./samples/short'))),
    #     settings=voice_settings
    # )



    with open(f'./essays/{title}.txt', 'r') as file:
        text = file.read()

        audio = generate(
            text=text,
            voice=voice,
            model="eleven_multilingual_v2"
        )

        save(audio, f'./voiced/{title}.mp3')



# Change the title of the essay to generate a voiceover for it
title = "Hackers And Painters"

# generate_essay_voiceover(title)
